/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 68cf13732e21eea9540253d64c9a4c5d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env {
		EMAIL: SendEmail;
		AI: Ai;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
	}
}
interface Env extends Cloudflare.Env {}
