/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: e0e5c829a6736d46eae62717805f24e4)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "MyAgent";
	}
	interface Env {
		EMAIL: SendEmail;
		AI: Ai;
		MyAgent: DurableObjectNamespace<import("./src/server").MyAgent>;
	}
}
interface Env extends Cloudflare.Env {}
